### ISSUE TITLE
Consider upgrading the rand crate to a version >= 0.5 

### ISSUE THREAD

**Issue by huitseeker** [zkcrypto/pairing#105]
The rand crate hereby used is 0.4, while the latest is is now 0.7 and most downstream Rust projects are upgraded to 0.6.x. Specifically the Rand trait is deprecated.

See also https://github.com/zcash/librustzcash/issues/60 and the [Upgrade guide](https://rust-random.github.io/book/update.html)

**Comment by burdges** [comment]
Appears done in https://github.com/zcash/librustzcash/issues/60

**Comment by str4d** [comment]
We will be upstreaming our changes from https://github.com/zcash/librustzcash shortly.

**Comment by str4d** [comment]
This has been done.
