### ISSUE TITLE
no_std support

### ISSUE THREAD

**Issue by ibalajiarun** [zkcrypto/pairing#111]
There exists Rust SDK (https://github.com/apache/incubator-teaclave-sgx-sdk) for developing enclave applications targeting Intel SGX. This lets developers build  applications in Rust that can run inside a trusted execution environment providing isolation and memory protection. To be used with the Rust SGX SDK, Rust libraries must not depend on std or should work with the std library provided with the SGX SDK. 

This library is used in various places including here: https://github.com/poanetwork/threshold_crypto/issues/67.

Please make pairing support no_std.

**Comment by str4d** [comment]
This will be closed by #115.

**Comment by str4d** [comment]
Correction: this *has* been closed by #115!
