### ISSUE TITLE
Updating rand

### ISSUE THREAD

**Issue by dignifiedquire** [zkcrypto/pairing#99]
Rand is at 0.6, while this crate and others around it are still at 0.4. This results in conflicts when I try to use it in combination with other crates which already depend on 0.5 or 0.6. 

Would a PR updating to `0.6` be accepted?

**Comment by daira** [comment]
Fixed in the librustzcash refactor by https://github.com/zcash/librustzcash/pull/91 .

**Comment by str4d** [comment]
This has been done.
